# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CasierConnect', '0002_casieruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casieruser',
            name='casier_user',
        ),
        migrations.DeleteModel(
            name='CasierUser',
        ),
    ]
