# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CasierConnect', '0003_auto_20160517_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casier',
            name='user',
        ),
    ]
