# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CasierConnect', '0006_auto_20160518_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casier',
            name='objet',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
