# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CasierConnect', '0007_auto_20160518_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casier',
            name='nom_casier',
        ),
    ]
